#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 20, 2020 11:44:42 PM +0300  platform: Windows NT

import sys
import uuid
import clientBL

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def fe_want_to_play_res(status_code, status_txt, game_number, score, opponentUsername, opponentScore, opponentGameNumber):
    global w
    print('fe_want_to_play_res')
    sys.stdout.flush()
    src = w.error_Label
    if status_code == "08":
        src.configure(text=status_txt + " (" + status_code + ")")
    else:
        src.configure(text=opponentUsername)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    clientBL.want_to_play(fe_want_to_play_res, "00", uuid.uuid4())

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import XOPage
    XOPage.vp_start_gui()




