#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 20, 2020 11:50:37 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import XOPage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    XOPage_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    XOPage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font13 = "-family {Tw Cen MT} -size 72 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Tw Cen MT} -size 40 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x451+650+150")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.067, rely=0.044, relheight=0.896
                , relwidth=0.872)
        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#408080")
        self.Frame1.configure(highlightbackground="#408080")
        self.Frame1.configure(highlightcolor="#408080")

        self.TSeparator1 = ttk.Separator(self.Frame1)
        self.TSeparator1.place(relx=0.379, rely=0.173, relheight=0.817)
        self.TSeparator1.configure(orient="vertical")

        self.TSeparator2 = ttk.Separator(self.Frame1)
        self.TSeparator2.place(relx=0.625, rely=0.198, relheight=0.792)
        self.TSeparator2.configure(orient="vertical")

        self.TSeparator3 = ttk.Separator(self.Frame1)
        self.TSeparator3.place(relx=0.153, rely=0.446, relwidth=0.707)

        self.TSeparator3_1 = ttk.Separator(self.Frame1)
        self.TSeparator3_1.place(relx=0.153, rely=0.718, relwidth=0.707)

        self.XO_Label = ttk.Label(self.Frame1)
        self.XO_Label.place(relx=0.287, rely=0.025, height=69, width=245)
        self.XO_Label.configure(background="#408080")
        self.XO_Label.configure(foreground="#ffffff")
        self.XO_Label.configure(font=font9)
        self.XO_Label.configure(relief="flat")
        self.XO_Label.configure(text='''X/O play!''')

        self.error_Label = ttk.Label(self.Frame1)
        self.error_Label.place(relx=0.05, rely=0.025, height=80, width=600)
        self.error_Label.configure(background="#408080")
        self.error_Label.configure(foreground="#ffffff")
        self.error_Label.configure(font="-family {Tw Cen MT} -size 14 -weight bold")
        self.error_Label.configure(relief="flat")
        self.error_Label.configure(text="vvvvvvvv")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.153, rely=0.198, height=94, width=107)
        self.Button1.configure(activebackground="#408080")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#408080")
        self.Button1.configure(anchor='s')
        self.Button1.configure(background="#408080")
        self.Button1.configure(cursor="fleur")
        self.Button1.configure(disabledforeground="#408080")
        self.Button1.configure(font=font13)
        self.Button1.configure(foreground="#408080")
        self.Button1.configure(highlightbackground="#408080")
        self.Button1.configure(highlightcolor="#408080")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="flat")

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.402, rely=0.198, height=94, width=107)
        self.Button2.configure(activebackground="#408080")
        self.Button2.configure(activeforeground="white")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(anchor='s')
        self.Button2.configure(background="#408080")
        self.Button2.configure(disabledforeground="#408080")
        self.Button2.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button2.configure(foreground="#408080")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(relief="flat")

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.65, rely=0.198, height=94, width=107)
        self.Button3.configure(activebackground="#408080")
        self.Button3.configure(activeforeground="white")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(anchor='s')
        self.Button3.configure(background="#408080")
        self.Button3.configure(disabledforeground="#408080")
        self.Button3.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button3.configure(foreground="#408080")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(relief="flat")

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.153, rely=0.47, height=94, width=107)
        self.Button4.configure(activebackground="#408080")
        self.Button4.configure(activeforeground="white")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(anchor='s')
        self.Button4.configure(background="#408080")
        self.Button4.configure(disabledforeground="#408080")
        self.Button4.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button4.configure(foreground="#408080")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(relief="flat")

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.402, rely=0.47, height=94, width=107)
        self.Button5.configure(activebackground="#408080")
        self.Button5.configure(activeforeground="white")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(anchor='s')
        self.Button5.configure(background="#408080")
        self.Button5.configure(disabledforeground="#408080")
        self.Button5.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button5.configure(foreground="#408080")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(relief="flat")

        self.Button6 = tk.Button(self.Frame1)
        self.Button6.place(relx=0.65, rely=0.47, height=94, width=107)
        self.Button6.configure(activebackground="#408080")
        self.Button6.configure(activeforeground="white")
        self.Button6.configure(activeforeground="black")
        self.Button6.configure(anchor='s')
        self.Button6.configure(background="#408080")
        self.Button6.configure(disabledforeground="#408080")
        self.Button6.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button6.configure(foreground="#408080")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(relief="flat")

        self.Button7 = tk.Button(self.Frame1)
        self.Button7.place(relx=0.153, rely=0.743, height=94, width=107)
        self.Button7.configure(activebackground="#408080")
        self.Button7.configure(activeforeground="white")
        self.Button7.configure(activeforeground="black")
        self.Button7.configure(anchor='s')
        self.Button7.configure(background="#408080")
        self.Button7.configure(disabledforeground="#408080")
        self.Button7.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button7.configure(foreground="#408080")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(relief="flat")

        self.Button8 = tk.Button(self.Frame1)
        self.Button8.place(relx=0.402, rely=0.743, height=94, width=107)
        self.Button8.configure(activebackground="#408080")
        self.Button8.configure(activeforeground="white")
        self.Button8.configure(activeforeground="black")
        self.Button8.configure(anchor='s')
        self.Button8.configure(background="#408080")
        self.Button8.configure(disabledforeground="#408080")
        self.Button8.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button8.configure(foreground="#408080")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(relief="flat")

        self.Button9 = tk.Button(self.Frame1)
        self.Button9.place(relx=0.65, rely=0.743, height=94, width=107)
        self.Button9.configure(activebackground="#408080")
        self.Button9.configure(activeforeground="white")
        self.Button9.configure(activeforeground="black")
        self.Button9.configure(anchor='s')
        self.Button9.configure(background="#408080")
        self.Button9.configure(disabledforeground="#408080")
        self.Button9.configure(font="-family {Tw Cen MT} -size 72 -weight bold")
        self.Button9.configure(foreground="#408080")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(relief="flat")

if __name__ == '__main__':
    vp_start_gui()





