#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 28, 2020 01:39:49 PM +0300  platform: Windows NT

import sys
import clientBL
import uuid

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def fe_want_to_play_res(status_code, status_txt, game_number, score, opponentUsername, opponentScore, serverGameNumber):
    global w
    print('fe_want_to_play_res')
    sys.stdout.flush()
    opponentName_Label = w.opponentName_Label
    opponentScore_Label= w.opponentScore_Label
    userScore_Label= w.userScore_Label
    symbol_Label=w.symbol_Label
    global symbol
    global turn
    if status_code == "08":
        opponentName_Label.configure(text=status_txt + " (" + status_code + ")")
        symbol = "X"
        #enableButtons(True)
    else:
        global _opponent_user_name
        _opponent_user_name = opponentUsername
        opponentName_Label.configure(text= "opponent: "+opponentUsername)
        opponentScore_Label.configure(text="opponent score: " + opponentScore)
        userScore_Label.configure(text="my score: " + score)
        if symbol == None:
            symbol = "O"
        symbol_Label.configure(text="you are: " + symbol)
        #enableButtons(False)
        global _serverGameNumber
        _serverGameNumber = serverGameNumber
        #clientBL.set_play_XO_callback(fe_XO_play_res, _serverGameNumber)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    clientBL.want_to_play(fe_want_to_play_res, "01", uuid.uuid4())

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import fourInARowPage
    fourInARowPage.vp_start_gui()




