#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Apr 28, 2020 07:03:52 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x450+454+177
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background #3c8867 -height 265 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 305 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground #ffffff \
        -background #3c8867 -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 36 -weight bold} -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Four In A Row play!} 
    vTcl:DefineAlias "$site_3_0.lab44" "for_in_a_row_Label" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe45 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe45" "TSeparator1_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe47 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe47" "TSeparator1_2" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe48 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe48" "TSeparator1_3" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe49 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe49" "TSeparator1_4" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe50 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe50" "TSeparator1_5" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe54 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe54" "TSeparator1_6" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe56
    vTcl:DefineAlias "$site_3_0.tSe56" "TSeparator7" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab89 \
        -activebackground #f9f9f9 -activeforeground black -background #3c8867 \
        -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 15 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left 
    vTcl:DefineAlias "$site_3_0.lab89" "symbol_Label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab90 \
        -activebackground #f9f9f9 -activeforeground black -background #3c8867 \
        -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 15 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left 
    vTcl:DefineAlias "$site_3_0.lab90" "opponent_username_Label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab91 \
        -activebackground #f9f9f9 -activeforeground black -background #3c8867 \
        -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 15 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left 
    vTcl:DefineAlias "$site_3_0.lab91" "opponent_score_Label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab92 \
        -activebackground #f9f9f9 -activeforeground black -background #3c8867 \
        -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 15 -weight bold} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left 
    vTcl:DefineAlias "$site_3_0.lab92" "user_score_Label" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra43 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra43" "Frame2_0" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra48 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra48" "Frame2_1" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra69 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra69" "Frame2_2" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra77 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra77" "Frame2_3" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra79 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra79" "Frame2_4" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra80 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra80" "Frame2_5" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra81 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra81" "Frame2_6" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra82 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra82" "Frame2_7" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra83 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra83" "Frame2_8" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra84 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra84" "Frame2_9" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra86 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra86" "Frame2_10" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra87 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra87" "Frame2_11" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra88 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra88" "Frame2_12" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra89 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra89" "Frame2_13" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra90 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra90" "Frame2_14" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra91 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra91" "Frame2_15" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra92 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra92" "Frame2_16" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra93 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra93" "Frame2_17" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra94 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra94" "Frame2_18" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra95 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra95" "Frame2_19" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra96 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra96" "Frame2_20" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra97 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra97" "Frame2_21" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra101 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra101" "Frame2_22" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra102 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra102" "Frame2_23" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.fra103 \
        -borderwidth 2 -relief groove -background #3c8867 -height 45 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 45 
    vTcl:DefineAlias "$site_3_0.fra103" "Frame2_24" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but104 \
        -background #eb0214 -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but104" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but105 \
        -activebackground #f9f9f9 -activeforeground black -background #eb0214 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but105" "Button2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but106 \
        -activebackground #f9f9f9 -activeforeground black -background #eb0214 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but106" "Button3" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but107 \
        -activebackground #f9f9f9 -activeforeground black -background #eb0214 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but107" "Button4" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but108 \
        -activebackground #f9f9f9 -activeforeground black -background #eb0214 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 
    vTcl:DefineAlias "$site_3_0.but108" "Button5" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 90 -y 20 -width 404 -relwidth 0 -height 71 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe45 \
        -in $site_3_0 -x 505 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe47 \
        -in $site_3_0 -x 443 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe48 \
        -in $site_3_0 -x 383 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe49 \
        -in $site_3_0 -x 323 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe50 \
        -in $site_3_0 -x 263 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe54 \
        -in $site_3_0 -x 200 -y 110 -width 2 -height 270 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tSe56 \
        -in $site_3_0 -x 199 -y 379 -width 310 -height 2 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab89 \
        -in $site_3_0 -x 30 -y 160 -width 154 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab90 \
        -in $site_3_0 -x 30 -y 260 -width 154 -height 51 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab91 \
        -in $site_3_0 -x 30 -y 320 -width 154 -height 51 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab92 \
        -in $site_3_0 -x 30 -y 180 -width 154 -height 51 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra43 \
        -in $site_3_0 -x 210 -y 330 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra48 \
        -in $site_3_0 -x 210 -y 280 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra69 \
        -in $site_3_0 -x 210 -y 230 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra77 \
        -in $site_3_0 -x 210 -y 180 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra79 \
        -in $site_3_0 -x 210 -y 130 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra80 \
        -in $site_3_0 -x 270 -y 330 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra81 \
        -in $site_3_0 -x 270 -y 280 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra82 \
        -in $site_3_0 -x 270 -y 230 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra83 \
        -in $site_3_0 -x 270 -y 180 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra84 \
        -in $site_3_0 -x 270 -y 130 -width 45 -relwidth 0 -height 45 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra86 \
        -in $site_3_0 -x 330 -y 330 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra87 \
        -in $site_3_0 -x 330 -y 280 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra88 \
        -in $site_3_0 -x 330 -y 230 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra89 \
        -in $site_3_0 -x 330 -y 180 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra90 \
        -in $site_3_0 -x 330 -y 130 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra91 \
        -in $site_3_0 -x 390 -y 330 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra92 \
        -in $site_3_0 -x 390 -y 280 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra93 \
        -in $site_3_0 -x 390 -y 230 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra94 \
        -in $site_3_0 -x 390 -y 180 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra95 \
        -in $site_3_0 -x 390 -y 130 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra96 \
        -in $site_3_0 -x 450 -y 330 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra97 \
        -in $site_3_0 -x 450 -y 280 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra101 \
        -in $site_3_0 -x 450 -y 230 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra102 \
        -in $site_3_0 -x 450 -y 180 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.fra103 \
        -in $site_3_0 -x 450 -y 130 -width 45 -height 45 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but104 \
        -in $site_3_0 -x 210 -y 80 -width 47 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but105 \
        -in $site_3_0 -x 270 -y 80 -width 47 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but106 \
        -in $site_3_0 -x 330 -y 80 -width 47 -height 44 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but107 \
        -in $site_3_0 -x 390 -y 80 -width 47 -height 44 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but108 \
        -in $site_3_0 -x 450 -y 80 -width 47 -height 44 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 40 -y 20 -width 523 -relwidth 0 -height 403 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

