#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 28, 2020 07:03:50 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import fourInARowPage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    fourInARowPage_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    fourInARowPage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+454+177")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.067, rely=0.044, relheight=0.896
                , relwidth=0.872)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#3c8867")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.for_in_a_row_Label = tk.Label(self.Frame1)
        self.for_in_a_row_Label.place(relx=0.172, rely=0.05, height=71
                , width=404)
        self.for_in_a_row_Label.configure(activebackground="#f9f9f9")
        self.for_in_a_row_Label.configure(activeforeground="#ffffff")
        self.for_in_a_row_Label.configure(background="#3c8867")
        self.for_in_a_row_Label.configure(disabledforeground="#a3a3a3")
        self.for_in_a_row_Label.configure(font="-family {Tw Cen MT} -size 36 -weight bold")
        self.for_in_a_row_Label.configure(foreground="#ffffff")
        self.for_in_a_row_Label.configure(highlightbackground="#d9d9d9")
        self.for_in_a_row_Label.configure(highlightcolor="black")
        self.for_in_a_row_Label.configure(text='''Four In A Row play!''')

        self.TSeparator1_1 = ttk.Separator(self.Frame1)
        self.TSeparator1_1.place(relx=0.966, rely=0.273, relheight=0.67)
        self.TSeparator1_1.configure(orient="vertical")

        self.TSeparator1_2 = ttk.Separator(self.Frame1)
        self.TSeparator1_2.place(relx=0.847, rely=0.273, relheight=0.67)
        self.TSeparator1_2.configure(orient="vertical")

        self.TSeparator1_3 = ttk.Separator(self.Frame1)
        self.TSeparator1_3.place(relx=0.732, rely=0.273, relheight=0.67)
        self.TSeparator1_3.configure(orient="vertical")

        self.TSeparator1_4 = ttk.Separator(self.Frame1)
        self.TSeparator1_4.place(relx=0.618, rely=0.273, relheight=0.67)
        self.TSeparator1_4.configure(orient="vertical")

        self.TSeparator1_5 = ttk.Separator(self.Frame1)
        self.TSeparator1_5.place(relx=0.503, rely=0.273, relheight=0.67)
        self.TSeparator1_5.configure(orient="vertical")

        self.TSeparator1_6 = ttk.Separator(self.Frame1)
        self.TSeparator1_6.place(relx=0.382, rely=0.273, relheight=0.67)
        self.TSeparator1_6.configure(orient="vertical")

        self.TSeparator7 = ttk.Separator(self.Frame1)
        self.TSeparator7.place(relx=0.38, rely=0.94, relwidth=0.593)

        self.symbol_Label = tk.Label(self.Frame1)
        self.symbol_Label.place(relx=0.057, rely=0.397, height=51, width=154)
        self.symbol_Label.configure(activebackground="#f9f9f9")
        self.symbol_Label.configure(activeforeground="black")
        self.symbol_Label.configure(background="#3c8867")
        self.symbol_Label.configure(disabledforeground="#a3a3a3")
        self.symbol_Label.configure(font="-family {Tw Cen MT} -size 15 -weight bold")
        self.symbol_Label.configure(foreground="#000000")
        self.symbol_Label.configure(highlightbackground="#d9d9d9")
        self.symbol_Label.configure(highlightcolor="black")
        self.symbol_Label.configure(justify='left')

        self.opponent_username_Label = tk.Label(self.Frame1)
        self.opponent_username_Label.place(relx=0.057, rely=0.645, height=51
                , width=154)
        self.opponent_username_Label.configure(activebackground="#f9f9f9")
        self.opponent_username_Label.configure(activeforeground="black")
        self.opponent_username_Label.configure(background="#3c8867")
        self.opponent_username_Label.configure(disabledforeground="#a3a3a3")
        self.opponent_username_Label.configure(font="-family {Tw Cen MT} -size 15 -weight bold")
        self.opponent_username_Label.configure(foreground="#000000")
        self.opponent_username_Label.configure(highlightbackground="#d9d9d9")
        self.opponent_username_Label.configure(highlightcolor="black")
        self.opponent_username_Label.configure(justify='left')

        self.opponent_score_Label = tk.Label(self.Frame1)
        self.opponent_score_Label.place(relx=0.057, rely=0.794, height=51
                , width=154)
        self.opponent_score_Label.configure(activebackground="#f9f9f9")
        self.opponent_score_Label.configure(activeforeground="black")
        self.opponent_score_Label.configure(background="#3c8867")
        self.opponent_score_Label.configure(disabledforeground="#a3a3a3")
        self.opponent_score_Label.configure(font="-family {Tw Cen MT} -size 15 -weight bold")
        self.opponent_score_Label.configure(foreground="#000000")
        self.opponent_score_Label.configure(highlightbackground="#d9d9d9")
        self.opponent_score_Label.configure(highlightcolor="black")
        self.opponent_score_Label.configure(justify='left')

        self.user_score_Label = tk.Label(self.Frame1)
        self.user_score_Label.place(relx=0.057, rely=0.447, height=51, width=154)

        self.user_score_Label.configure(activebackground="#f9f9f9")
        self.user_score_Label.configure(activeforeground="black")
        self.user_score_Label.configure(background="#3c8867")
        self.user_score_Label.configure(disabledforeground="#a3a3a3")
        self.user_score_Label.configure(font="-family {Tw Cen MT} -size 15 -weight bold")
        self.user_score_Label.configure(foreground="#000000")
        self.user_score_Label.configure(highlightbackground="#d9d9d9")
        self.user_score_Label.configure(highlightcolor="black")
        self.user_score_Label.configure(justify='left')

        self.Frame2_0 = tk.Frame(self.Frame1)
        self.Frame2_0.place(relx=0.402, rely=0.819, relheight=0.112
                , relwidth=0.086)
        self.Frame2_0.configure(relief='groove')
        self.Frame2_0.configure(borderwidth="2")
        self.Frame2_0.configure(relief="groove")
        self.Frame2_0.configure(background="#3c8867")

        self.Frame2_1 = tk.Frame(self.Frame1)
        self.Frame2_1.place(relx=0.402, rely=0.695, relheight=0.112
                , relwidth=0.086)
        self.Frame2_1.configure(relief='groove')
        self.Frame2_1.configure(borderwidth="2")
        self.Frame2_1.configure(relief="groove")
        self.Frame2_1.configure(background="#3c8867")
        self.Frame2_1.configure(highlightbackground="#d9d9d9")
        self.Frame2_1.configure(highlightcolor="black")

        self.Frame2_2 = tk.Frame(self.Frame1)
        self.Frame2_2.place(relx=0.402, rely=0.571, relheight=0.112
                , relwidth=0.086)
        self.Frame2_2.configure(relief='groove')
        self.Frame2_2.configure(borderwidth="2")
        self.Frame2_2.configure(relief="groove")
        self.Frame2_2.configure(background="#3c8867")
        self.Frame2_2.configure(highlightbackground="#d9d9d9")
        self.Frame2_2.configure(highlightcolor="black")

        self.Frame2_3 = tk.Frame(self.Frame1)
        self.Frame2_3.place(relx=0.402, rely=0.447, relheight=0.112
                , relwidth=0.086)
        self.Frame2_3.configure(relief='groove')
        self.Frame2_3.configure(borderwidth="2")
        self.Frame2_3.configure(relief="groove")
        self.Frame2_3.configure(background="#3c8867")
        self.Frame2_3.configure(highlightbackground="#d9d9d9")
        self.Frame2_3.configure(highlightcolor="black")

        self.Frame2_4 = tk.Frame(self.Frame1)
        self.Frame2_4.place(relx=0.402, rely=0.323, relheight=0.112
                , relwidth=0.086)
        self.Frame2_4.configure(relief='groove')
        self.Frame2_4.configure(borderwidth="2")
        self.Frame2_4.configure(relief="groove")
        self.Frame2_4.configure(background="#3c8867")
        self.Frame2_4.configure(highlightbackground="#d9d9d9")
        self.Frame2_4.configure(highlightcolor="black")

        self.Frame2_5 = tk.Frame(self.Frame1)
        self.Frame2_5.place(relx=0.516, rely=0.819, relheight=0.112
                , relwidth=0.086)
        self.Frame2_5.configure(relief='groove')
        self.Frame2_5.configure(borderwidth="2")
        self.Frame2_5.configure(relief="groove")
        self.Frame2_5.configure(background="#3c8867")
        self.Frame2_5.configure(highlightbackground="#d9d9d9")
        self.Frame2_5.configure(highlightcolor="black")

        self.Frame2_6 = tk.Frame(self.Frame1)
        self.Frame2_6.place(relx=0.516, rely=0.695, relheight=0.112
                , relwidth=0.086)
        self.Frame2_6.configure(relief='groove')
        self.Frame2_6.configure(borderwidth="2")
        self.Frame2_6.configure(relief="groove")
        self.Frame2_6.configure(background="#3c8867")
        self.Frame2_6.configure(highlightbackground="#d9d9d9")
        self.Frame2_6.configure(highlightcolor="black")

        self.Frame2_7 = tk.Frame(self.Frame1)
        self.Frame2_7.place(relx=0.516, rely=0.571, relheight=0.112
                , relwidth=0.086)
        self.Frame2_7.configure(relief='groove')
        self.Frame2_7.configure(borderwidth="2")
        self.Frame2_7.configure(relief="groove")
        self.Frame2_7.configure(background="#3c8867")
        self.Frame2_7.configure(highlightbackground="#d9d9d9")
        self.Frame2_7.configure(highlightcolor="black")

        self.Frame2_8 = tk.Frame(self.Frame1)
        self.Frame2_8.place(relx=0.516, rely=0.447, relheight=0.112
                , relwidth=0.086)
        self.Frame2_8.configure(relief='groove')
        self.Frame2_8.configure(borderwidth="2")
        self.Frame2_8.configure(relief="groove")
        self.Frame2_8.configure(background="#3c8867")
        self.Frame2_8.configure(highlightbackground="#d9d9d9")
        self.Frame2_8.configure(highlightcolor="black")

        self.Frame2_9 = tk.Frame(self.Frame1)
        self.Frame2_9.place(relx=0.516, rely=0.323, relheight=0.112
                , relwidth=0.086)
        self.Frame2_9.configure(relief='groove')
        self.Frame2_9.configure(borderwidth="2")
        self.Frame2_9.configure(relief="groove")
        self.Frame2_9.configure(background="#3c8867")
        self.Frame2_9.configure(highlightbackground="#d9d9d9")
        self.Frame2_9.configure(highlightcolor="black")

        self.Frame2_10 = tk.Frame(self.Frame1)
        self.Frame2_10.place(relx=0.631, rely=0.819, relheight=0.112
                , relwidth=0.086)
        self.Frame2_10.configure(relief='groove')
        self.Frame2_10.configure(borderwidth="2")
        self.Frame2_10.configure(relief="groove")
        self.Frame2_10.configure(background="#3c8867")
        self.Frame2_10.configure(highlightbackground="#d9d9d9")
        self.Frame2_10.configure(highlightcolor="black")

        self.Frame2_11 = tk.Frame(self.Frame1)
        self.Frame2_11.place(relx=0.631, rely=0.695, relheight=0.112
                , relwidth=0.086)
        self.Frame2_11.configure(relief='groove')
        self.Frame2_11.configure(borderwidth="2")
        self.Frame2_11.configure(relief="groove")
        self.Frame2_11.configure(background="#3c8867")
        self.Frame2_11.configure(highlightbackground="#d9d9d9")
        self.Frame2_11.configure(highlightcolor="black")

        self.Frame2_12 = tk.Frame(self.Frame1)
        self.Frame2_12.place(relx=0.631, rely=0.571, relheight=0.112
                , relwidth=0.086)
        self.Frame2_12.configure(relief='groove')
        self.Frame2_12.configure(borderwidth="2")
        self.Frame2_12.configure(relief="groove")
        self.Frame2_12.configure(background="#3c8867")
        self.Frame2_12.configure(highlightbackground="#d9d9d9")
        self.Frame2_12.configure(highlightcolor="black")

        self.Frame2_13 = tk.Frame(self.Frame1)
        self.Frame2_13.place(relx=0.631, rely=0.447, relheight=0.112
                , relwidth=0.086)
        self.Frame2_13.configure(relief='groove')
        self.Frame2_13.configure(borderwidth="2")
        self.Frame2_13.configure(relief="groove")
        self.Frame2_13.configure(background="#3c8867")
        self.Frame2_13.configure(highlightbackground="#d9d9d9")
        self.Frame2_13.configure(highlightcolor="black")

        self.Frame2_14 = tk.Frame(self.Frame1)
        self.Frame2_14.place(relx=0.631, rely=0.323, relheight=0.112
                , relwidth=0.086)
        self.Frame2_14.configure(relief='groove')
        self.Frame2_14.configure(borderwidth="2")
        self.Frame2_14.configure(relief="groove")
        self.Frame2_14.configure(background="#3c8867")
        self.Frame2_14.configure(highlightbackground="#d9d9d9")
        self.Frame2_14.configure(highlightcolor="black")

        self.Frame2_15 = tk.Frame(self.Frame1)
        self.Frame2_15.place(relx=0.746, rely=0.819, relheight=0.112
                , relwidth=0.086)
        self.Frame2_15.configure(relief='groove')
        self.Frame2_15.configure(borderwidth="2")
        self.Frame2_15.configure(relief="groove")
        self.Frame2_15.configure(background="#3c8867")
        self.Frame2_15.configure(highlightbackground="#d9d9d9")
        self.Frame2_15.configure(highlightcolor="black")

        self.Frame2_16 = tk.Frame(self.Frame1)
        self.Frame2_16.place(relx=0.746, rely=0.695, relheight=0.112
                , relwidth=0.086)
        self.Frame2_16.configure(relief='groove')
        self.Frame2_16.configure(borderwidth="2")
        self.Frame2_16.configure(relief="groove")
        self.Frame2_16.configure(background="#3c8867")
        self.Frame2_16.configure(highlightbackground="#d9d9d9")
        self.Frame2_16.configure(highlightcolor="black")

        self.Frame2_17 = tk.Frame(self.Frame1)
        self.Frame2_17.place(relx=0.746, rely=0.571, relheight=0.112
                , relwidth=0.086)
        self.Frame2_17.configure(relief='groove')
        self.Frame2_17.configure(borderwidth="2")
        self.Frame2_17.configure(relief="groove")
        self.Frame2_17.configure(background="#3c8867")
        self.Frame2_17.configure(highlightbackground="#d9d9d9")
        self.Frame2_17.configure(highlightcolor="black")

        self.Frame2_18 = tk.Frame(self.Frame1)
        self.Frame2_18.place(relx=0.746, rely=0.447, relheight=0.112
                , relwidth=0.086)
        self.Frame2_18.configure(relief='groove')
        self.Frame2_18.configure(borderwidth="2")
        self.Frame2_18.configure(relief="groove")
        self.Frame2_18.configure(background="#3c8867")
        self.Frame2_18.configure(highlightbackground="#d9d9d9")
        self.Frame2_18.configure(highlightcolor="black")

        self.Frame2_19 = tk.Frame(self.Frame1)
        self.Frame2_19.place(relx=0.746, rely=0.323, relheight=0.112
                , relwidth=0.086)
        self.Frame2_19.configure(relief='groove')
        self.Frame2_19.configure(borderwidth="2")
        self.Frame2_19.configure(relief="groove")
        self.Frame2_19.configure(background="#3c8867")
        self.Frame2_19.configure(highlightbackground="#d9d9d9")
        self.Frame2_19.configure(highlightcolor="black")

        self.Frame2_20 = tk.Frame(self.Frame1)
        self.Frame2_20.place(relx=0.86, rely=0.819, relheight=0.112
                , relwidth=0.086)
        self.Frame2_20.configure(relief='groove')
        self.Frame2_20.configure(borderwidth="2")
        self.Frame2_20.configure(relief="groove")
        self.Frame2_20.configure(background="#3c8867")
        self.Frame2_20.configure(highlightbackground="#d9d9d9")
        self.Frame2_20.configure(highlightcolor="black")

        self.Frame2_21 = tk.Frame(self.Frame1)
        self.Frame2_21.place(relx=0.86, rely=0.695, relheight=0.112
                , relwidth=0.086)
        self.Frame2_21.configure(relief='groove')
        self.Frame2_21.configure(borderwidth="2")
        self.Frame2_21.configure(relief="groove")
        self.Frame2_21.configure(background="#3c8867")
        self.Frame2_21.configure(highlightbackground="#d9d9d9")
        self.Frame2_21.configure(highlightcolor="black")

        self.Frame2_22 = tk.Frame(self.Frame1)
        self.Frame2_22.place(relx=0.86, rely=0.571, relheight=0.112
                , relwidth=0.086)
        self.Frame2_22.configure(relief='groove')
        self.Frame2_22.configure(borderwidth="2")
        self.Frame2_22.configure(relief="groove")
        self.Frame2_22.configure(background="#3c8867")
        self.Frame2_22.configure(highlightbackground="#d9d9d9")
        self.Frame2_22.configure(highlightcolor="black")

        self.Frame2_23 = tk.Frame(self.Frame1)
        self.Frame2_23.place(relx=0.86, rely=0.447, relheight=0.112
                , relwidth=0.086)
        self.Frame2_23.configure(relief='groove')
        self.Frame2_23.configure(borderwidth="2")
        self.Frame2_23.configure(relief="groove")
        self.Frame2_23.configure(background="#3c8867")
        self.Frame2_23.configure(highlightbackground="#d9d9d9")
        self.Frame2_23.configure(highlightcolor="black")

        self.Frame2_24 = tk.Frame(self.Frame1)
        self.Frame2_24.place(relx=0.86, rely=0.323, relheight=0.112
                , relwidth=0.086)
        self.Frame2_24.configure(relief='groove')
        self.Frame2_24.configure(borderwidth="2")
        self.Frame2_24.configure(relief="groove")
        self.Frame2_24.configure(background="#3c8867")
        self.Frame2_24.configure(highlightbackground="#d9d9d9")
        self.Frame2_24.configure(highlightcolor="black")

        self.Button1 = tk.Button(self.Frame1)
        self.Button1.place(relx=0.402, rely=0.199, height=44, width=47)
        self.Button1.configure(activebackground="#3c8867")
        self.Button1.configure(activeforeground="white")
        self.Button1.configure(activeforeground="#3c8867")
        self.Button1.configure(background="#eb0214")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")

        self.Button2 = tk.Button(self.Frame1)
        self.Button2.place(relx=0.516, rely=0.199, height=44, width=47)
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(activeforeground="black")
        self.Button2.configure(background="#eb0214")
        self.Button2.configure(cursor="fleur")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")

        self.Button3 = tk.Button(self.Frame1)
        self.Button3.place(relx=0.631, rely=0.199, height=44, width=47)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(activeforeground="black")
        self.Button3.configure(background="#eb0214")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")

        self.Button4 = tk.Button(self.Frame1)
        self.Button4.place(relx=0.746, rely=0.199, height=44, width=47)
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(activeforeground="black")
        self.Button4.configure(background="#eb0214")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")

        self.Button5 = tk.Button(self.Frame1)
        self.Button5.place(relx=0.86, rely=0.199, height=44, width=47)
        self.Button5.configure(activebackground="#f9f9f9")
        self.Button5.configure(activeforeground="black")
        self.Button5.configure(background="#eb0214")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")

if __name__ == '__main__':
    vp_start_gui()





