#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Mar 23, 2020 03:58:34 PM +0200  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background #d5c0fa -height 345 \
        -width 545 
    vTcl:DefineAlias "$top.fra43" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra43
    entry $site_3_0.ent45 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent45" "username_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent46" "city_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$site_3_0.ent47" "birthYear_entry" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent49" "motherName_entry" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -background #d5c0fa -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 30 -weight bold} -foreground #ffffff \
        -text { Forget your password?} 
    vTcl:DefineAlias "$site_3_0.lab51" "forget_label" vTcl:WidgetProc "Toplevel1" 1
    ttk::label $site_3_0.tLa56 \
        -background #d5c0fa -foreground #ffffff \
        -font {-family {Tw Cen MT} -size 13 -weight bold} -relief flat \
        -text {In order to get your password, you should fill those details,
and then you will see your password in the command line
} 
    vTcl:DefineAlias "$site_3_0.tLa56" "inst_label" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but57 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #d5c0fa \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text finish 
    vTcl:DefineAlias "$site_3_0.but57" "finish_button" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #ffffff -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #d5c0fa \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text return 
    vTcl:DefineAlias "$site_3_0.but58" "return_button" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -background #d5c0fa -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #ffffff \
        -text username 
    vTcl:DefineAlias "$site_3_0.lab59" "username_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -background #d5c0fa -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #ffffff \
        -text city 
    vTcl:DefineAlias "$site_3_0.lab60" "city_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab61 \
        -background #d5c0fa -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #ffffff \
        -text {birth year} 
    vTcl:DefineAlias "$site_3_0.lab61" "birthYear_label" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -background #d5c0fa -disabledforeground #a3a3a3 \
        -font {-family {Tw Cen MT} -size 14 -weight bold} -foreground #ffffff \
        -text {mother's name} 
    vTcl:DefineAlias "$site_3_0.lab62" "mothername_label" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent45 \
        -in $site_3_0 -x 210 -y 170 -width 204 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 210 -y 210 -width 204 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 210 -y 250 -width 204 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 210 -y 290 -width 204 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 60 -y 40 -width 394 -relwidth 0 -height 51 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tLa56 \
        -in $site_3_0 -x 30 -y 110 -width 435 -relwidth 0 -height 39 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 90 -y 340 -width 131 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but58 \
        -in $site_3_0 -x 330 -y 340 -width 127 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 72 -y 170 -width 84 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 100 -y 210 -width 34 -relwidth 0 -height 31 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 70 -y 250 -width 86 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 60 -y 290 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 40 -y 20 -width 523 -relwidth 0 -height 403 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

