#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 27, 2020 03:20:17 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def set_results(status_code, status_txt, score, opponent_user_name, opponent_score):
    global w
    print (opponent_user_name)
    w.answer_Label.configure(text=status_txt)
    w.userScore_Label.configure(text="my score: " + score)
    w.opponentScore_Label.configure(text=opponent_user_name+ "'s score: " + opponent_score)


def open_choosePage():
    sys.stdout.flush()
    sys.path.append('..\\chooseGamePage')
    import chooseGamePage
    chooseGamePage.create_Toplevel1(root, 'Hello', top_level)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import resultPage
    resultPage.vp_start_gui()




