#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Apr 22, 2020 10:57:04 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import chooseGamePage_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    chooseGamePage_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    chooseGamePage_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Tw Cen MT} -size 48 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font12 = "-family {Tw Cen MT} -size 30 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Tw Cen MT} -size 40 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x450+650+150")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.05, rely=0.044, relheight=0.878, relwidth=0.925)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#678fed")

        self.label_choose = tk.Label(self.Frame1)
        self.label_choose.place(relx=0.18, rely=0.152, height=61, width=354)
        self.label_choose.configure(activeforeground="#678fed")
        self.label_choose.configure(background="#678fed")
        self.label_choose.configure(disabledforeground="#a3a3a3")
        self.label_choose.configure(font=font9)
        self.label_choose.configure(foreground="#ffffff")
        self.label_choose.configure(text='''Choose a game''')

        self.button_XO = tk.Button(self.Frame1)
        self.button_XO.place(relx=0.126, rely=0.405, height=174, width=187)
        self.button_XO.configure(activebackground="#ececec")
        self.button_XO.configure(activeforeground="#000000")
        self.button_XO.configure(background="#ffffff")
        self.button_XO.configure(command=chooseGamePage_support.startXOPage)
        self.button_XO.configure(disabledforeground="#a3a3a3")
        self.button_XO.configure(font=font10)
        self.button_XO.configure(foreground="#678fed")
        self.button_XO.configure(highlightbackground="#d9d9d9")
        self.button_XO.configure(highlightcolor="black")
        self.button_XO.configure(pady="0")
        self.button_XO.configure(text='''X/O''')

        self.button_4InARow = tk.Button(self.Frame1)
        self.button_4InARow.place(relx=0.577, rely=0.405, height=174, width=197)
        self.button_4InARow.configure(activebackground="#ececec")
        self.button_4InARow.configure(activeforeground="#000000")
        self.button_4InARow.configure(background="#ffffff")
        self.button_4InARow.configure(cursor="fleur")
        self.button_4InARow.configure(disabledforeground="#a3a3a3")
        self.button_4InARow.configure(font=font12)
        self.button_4InARow.configure(foreground="#678fed")
        self.button_4InARow.configure(highlightbackground="#d9d9d9")
        self.button_4InARow.configure(highlightcolor="black")
        self.button_4InARow.configure(pady="0")
        self.button_4InARow.configure(text='''4 In A Row''')

if __name__ == '__main__':
    vp_start_gui()





